# ====================================================== #
#                                                        #
#                                                        #
#          SimpleMessages made by BE Development         #
#                                                        #
#                                                        #
# ====================================================== #

# ==================================== #

# PlaceholderAPI compatible
# To use PlaceholderAPI placeholders, you must import them into PAPI through ecloud or extensions.

# ==================================== #

# Internal Placeholders:

# Death Messages:
# %death_player% - Who died
# %death_killer% - Who killed the person
# %death_item% - What item was used to kill
#
# Messaging System
# %message% - The message that is sent
# %sender%- The person who sent the message
# %receiver% - The person who receives the message
#
# All Messages:
# %version% - The current plugin version
# %player% - The player the message is sending to or who joined/left
# %playercount% - The amount of unique players that have joined

# ==================================== #

Main:
  Header: "&b&lSimpleMessages &ev%version%"
  Footer: "&b&lSimpleMessages &ev%version%"

Help:
  Header: "&b&lSimpleMessages &eHelp Menu"
  Footer: "&b&lSimpleMessages &eHelp Menu"

# ==================================== #

Motd:
  Enabled: true
# Enables/disables the motd

  Message:
    - "&bWelcome back &e%player%"
    - "&b&lSimpleMessages &eby https://bedev.tech"

# ==================================== #

Messaging:
# Format of the messages that are sent to players
  Messages:
    Incoming: "&f(&bYou &f> &b%receiver%&f)&8: &f%message%"
    Outgoing: "&f(&b%sender% &f> &bYou&f)&8: &f%message%"
# Errors that are sent to players
  Errors:
    NoConversation: "&cNot currently in a conversation!"
    PlayerNotOnline: "&cPlayer is not online!"

# ==================================== #

DeathMessage:
  Enabled: true
# Enables/disables death messages

  OnlyPlayer: true
# Enabling 'OnlyPlayer' will only send messages for if the player is killed by someone else and not natural eg: fall damage, drowning

  Message: "&6%death_player% &fwas killed by &6%death_killer% &fwith their &6%death_item%"

# ==================================== #

# FirstJoinmessage: the message sent to players when someone joins the game

FirstJoinMessage:
  Enabled: true
# Enables/disables first join messages

  Message: "&f%player% &ajoined the game for the first time! &8[&e#%playercount%&8]"

# ==================================== #

# Joinmessage: the message sent to players when someone joins the game

JoinMessage:
  Enabled: true
# Enables/disables join messages

  Message: "&f%player% &ajoined the game"

# ==================================== #

# LeaveMessage: the message sent to players when someone leaves the game

LeaveMessage:
  Enabled: true
# Enables/disables leave messages

  Message: "&f%player% &cleft the game"

# ==================================== #

Website:
  Enabled: true
# Enables/disables /website

  Message: "&aChange this in &econfig.yml"

# ==================================== #

Store:
  Enabled: true
# Enables/disables /store

  Message: "&aChange this in &econfig.yml"

# ==================================== #

Discord:
  Enabled: true
# Enables/disables /discord

  Message: "&aChange this in &econfig.yml"

# ==================================== #

Apply:
  Enabled: true
# Enables/disables /apply

  Message: "&aChange this in &econfig.yml"

# ==================================== #

TeamSpeak:
  Enabled: true
# Enables/disables /teamspeak

  Message: "&aChange this in &econfig.yml"

# ==================================== #

Twitter:
  Enabled: true
# Enables/disables /twitter

  Message: "&aChange this in &econfig.yml"

# ==================================== #

Twitch:
  Enabled: true
# Enables/disables /twitch

  Message: "&aChange this in &econfig.yml"

# ==================================== #

YouTube:
  Enabled: true
# Enables/disables /youtube

  Message: "&aChange this in &econfig.yml"

# ==================================== #