name: SimpleMessages
authors:
  - ElitestarsSam
version: 1.0.0
main: tech.bedev.SimpleMessages.Main
description: Customise loads of messages!
depend:
  - PlaceholderAPI
api-version: 1.13
website: https://bedev.tech
commands:
  motd:
    description: Motd command
  sm:
    description: Main command
    aliases:
      - simplemessages
  website:
    description: Website command
  store:
    description: Store command
  discord:
    description: Discord command
  apply:
    description: Apply command
  teamspeak:
    description: TeamSpeak command
    aliases:
      - ts
      - ts3
      - teamspeak3
  twitter:
    description: Twitter command
  twitch:
    description: Twitch command
  youtube:
    description: YouTube command
  tellraw:
    description: Better /tellraw command
  toggledeathmessages:
    description: Toggle death messages
    aliases:
      - deathmessages
      - dm
      - tdm
  msg:
    description: Message command
    aliases:
      - tell
      - w
      - t
      - whisper
      - message
  reply:
    description: Reply command
    aliases:
      - r
permissions:
  sm.commands.*:
    description: Allows use of all SimpleMessages commands
    children:
      sm.website: true
      sm.store: true
      sm.discord: true
      sm.apply: true
      sm.teamspeak: true
      sm.twitter: true
      sm.twitch: true
      sm.youtube: true
  sm.*:
    description: All permissions
    children:
      sm.commands.*: true
      sm.update: true
      sm.reload: true
      sm.help: true
      sm.motd: true
      sm.toggledeathmessages: true
  sm.update:
    default: op
  sm.reload:
    default: op
  sm.help:
    default: op
  sm.motd:
    default: true
  sm.website:
    description: Allows use of /website
    default: true
  sm.store:
    description: Allows use of /store
    default: true
  sm.discord:
    description: Allows use of /discord
    default: true
  sm.apply:
    description: Allows use of /apply
    default: true
  sm.teamspeak:
    description: Allows use of /teamspeak
    default: true
  sm.twitter:
    description: Allows use of /twitter
    default: true
  sm.twitch:
    description: Allows use of /twitch
    default: true
  sm.youtube:
    description: Allows use of /youtube
    default: true
  sm.toggledeathmessages:
    description: Ablility to toggle death messages
    default: true
  sm.msg:
    description: Allows use of /msg and /r
    default: true